# Alacritty Configuration
# Catppuccin Mocha Theme

# Window configuration
window:
  opacity: 0.9
  decorations: buttonless
  padding:
    x: 10
    y: 10
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true

# Font configuration
font:
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic
  size: 12.0

# Colors (Catppuccin Mocha)
colors:
  primary:
    background: '#1e1e2e'
    foreground: '#cdd6f4'
  cursor:
    text: '#1e1e2e'
    cursor: '#f5c2e7'
  normal:
    black: '#45475a'
    red: '#f38ba8'
    green: '#a6e3a1'
    yellow: '#f9e2af'
    blue: '#89b4fa'
    magenta: '#f5c2e7'
    cyan: '#94e2d5'
    white: '#bac2de'
  bright:
    black: '#585b70'
    red: '#f38ba8'
    green: '#a6e3a1'
    yellow: '#f9e2af'
    blue: '#89b4fa'
    magenta: '#f5c2e7'
    cyan: '#94e2d5'
    white: '#a6adc8'

# Cursor configuration
cursor:
  style: Beam

# Live config reload
live_config_reload: true

# Shell
shell:
  program: zsh

# Key bindings
key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: F11, action: ToggleFullscreen }

# Mouse bindings
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

# Selection
selection:
  save_to_clipboard: true 